update docker image path to docker pull include org
az-digital/digital.arizona.edu pull request #11
Opened 2020-09-25 21:54 UTC by kevcooper

2020-09-25 21:57 UTC, joeparsons approved these changes

2020-09-28 04:27 UTC, mmunro-ltrr commented
Shouldn't the org name be inserted before the repository name when defining the prefix (line 36), rather than in front of everything including the registry name? I think the syntax is `docker.pkg.github.com/org/repo/image:tag`, but it may all be obsolete anyway
https://github.blog/2020-09-01-introducing-github-container-registry/

2020-09-28 16:26 UTC, trackleft approved these changes

2020-09-28 20:00 UTC, joeparsons requested changes
I agree with @mmunro-ltrr that it'd be better to make this change on line 36.

2020-09-30 14:49 UTC, kevcooper reviewed
I've moved the change to line 36

2020-09-30 16:05 UTC, mmunro-ltrr approved these changes

2020-09-30 16:26 UTC, joeparsons approved these changes

2020-09-30 16:36 UTC, jwmoore1 approved these changes

2020-09-30 20:31 UTC, trackleft approved these changes

2020-09-30 22:36 UTC, merged