Use repository_dispatch
az-digital/digital.arizona.edu pull request #4
Opened 2020-09-16 21:57 UTC by kevcooper

See https://github.com/az-digital/arizona-bootstrap/issues/131

2020-09-16 22:01 UTC, joeparsons requested changes

2020-09-16 22:01 UTC, joeparsons commented on .github/workflows/release.yml
> +      - name: Build review site and sync
We should probably also rename this step to be `Build and deploy documentation site artifact` (not really a review site)

2020-09-16 22:03 UTC, joeparsons commented on .github/workflows/release.yml
> +      - name: Build review site and sync
Never mind.  I think you're already doing this in lines 19-20

2020-09-18 17:42 UTC, joeparsons approved these changes

2020-09-18 17:43 UTC, jwmoore1 approved these changes

2020-09-18 17:43 UTC, merged